In [1]:
import numpy as np

In [37]:
a = np.arange(0,121).reshape(11,11)

In [38]:
a

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20,  21],
       [ 22,  23,  24,  25,  26,  27,  28,  29,  30,  31,  32],
       [ 33,  34,  35,  36,  37,  38,  39,  40,  41,  42,  43],
       [ 44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54],
       [ 55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65],
       [ 66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76],
       [ 77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87],
       [ 88,  89,  90,  91,  92,  93,  94,  95,  96,  97,  98],
       [ 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
       [110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120]])

In [39]:
J = np.array([[0,1,0],
              [1,0,1],
              [0,1,0]])

In [52]:
def get_periodic_subarray(array, indices):
    i, j = indices
    n, m = np.shape(array)

    #subarray = np.zeros((3, 3))
    #for di in range(-1, 2):
    #    for dj in range(-1, 2):
    #        subarray[(di+1)%3, (dj+1)%3] = array[(i+di)%n, (j+dj)%m]
    
    di = np.arange(-1, 2)
    dj = np.arange(-1, 2)

    I, J = np.meshgrid((i + di) % n, (j + dj) % m, indexing='ij')
    print(I)
    print(J)

    return array[I, J]

In [53]:
q = get_periodic_subarray(a,np.array([10,10]))

[[ 9  9  9]
 [10 10 10]
 [ 0  0  0]]
[[ 9 10  0]
 [ 9 10  0]
 [ 9 10  0]]


In [54]:
print(q)

[[108 109  99]
 [119 120 110]
 [  9  10   0]]


In [76]:
s = 11

print(np.arange(-1,2))

[-1  0  1]


In [2]:
import numpy as np

In [6]:
print(np.random.choice([-1,1], p=(0.5,0.5)))

-1
